### PR TITLE
split into mod and cli tool

### PR DESCRIPTION
**Pull request by DonatJR**
PR for #9 
I just did the logging / printing change for now, please have a look at it and tell me if you are okay with it or if you maybe have a better idea...

### CODE REVIEW

**Comment by SailReal** [comment]
LGTM but if I understand it right, 
```rust
let result = sub_fn();
    if let Some(error) = result.err() {
        error!("adbackup finished with error: {}", error.to_string());
}
```
would print in the error-case nothing to the console? We have to use `println!? at this point, right? [adbackup-cli.rs#L34](https://github.com/DonatJR/adbackup/blob/129d131d5a0103ccebd08f3fdb16158526f5f018/src/bin/adbackup-cli.rs#L34)

**Comment by DonatJR** [comment]
yep, you are right on that one. I only changed to println for code I actually touched :/ will fix

**Comment by DonatJR** [comment]
with these new changes the cli tools writes only to stdout and the module writes only to the log-file, please have a look @SailReal

**Comment by SailReal** [comment]
Looks really amazing, thx for the improvement!

**Pull request merged**
